### ISSUE TITLE
not decoding secrets

### ISSUE THREAD

**Issue by jpriebe** [mfuentesg/ksd#13]
I just ran `go get github.com/mfuentesg/ksd` about 20 minutes ago (after your 1.0.2 release).

When I pipe a secrets yaml file through ksd, it doesn't modify the base64-encoded data at all.  Saving the output to a file and diffing with the original shows no differences between the two.

**Comment by mfuentesg** [comment]
can you give me an example?

**Comment by mfuentesg** [comment]
sorry man, i am working on the fix!

**Comment by jpriebe** [comment]
Thanks for the quick fix.  It could be my inexperience with go, but when I tried "go get", I didn't seem to get the latest version.  I cloned the repo and built, and it worked fine.
