### ISSUE TITLE
use stringData instead of data

### ISSUE THREAD

**Issue by jpriebe** [mfuentesg/ksd#15]
Just a suggestion:   when you decode the base64-encoded values under the "data" key, if you replaced "data" with "stringData", the resulting YAML file would be directly usable by kubernetes.

This is useful for situations where you are going to run your YAML through something like sops to allow you to securely store the YAML in git.  You want the YAML in a format that is legal for k8s so that when you decrypt from sops, you can feed the results directly to kubectl apply.

Of course, I realize that it's a pretty easy workaround.  After running ksd, I can manually edit the YAML to change "data" to "stringData".  This is just a small convenience kind of thing.

**Comment by jpriebe** [comment]
I ran across this in the kubectl-ksd project: https://github.com/ashleyschuett/kubernetes-secret-decode/issues/6.  Apparently, that tool originally left the b64-decoded values in the "data" key as well, but users felt like it was important to have it be in the "stringData" key.

**Comment by mohag** [comment]
The README examples should probably be updated.
