### ISSUE TITLE
KSD: Testing - Could you show me the way run your test as a part of README.md

### ISSUE THREAD

**Issue by thodquach** [mfuentesg/ksd#7]
Hello @mfuentesg ,
Could you show me the ways i can run your test?
Sr for bothering you but I a new comer in Go =))))
Tks in advance!!!

**Comment by mfuentesg** [comment]
hey @thodquach, yeah, no problem.

execute the following command
```
go test -race
```

**Comment by thodquach** [comment]
Tks @mfuentesg so much !!!
