### ISSUE TITLE
Unable to fetch decoded kubectl secrets using ksd

### ISSUE THREAD

**Issue by ansarkar-github** [mfuentesg/ksd#8]
As mentioned in README.md, installed ksd in my local fedora machine but it did not create executable.
Then tried go build in the ~/go/src/mfuentesg/ksd directory which created the executable.
Once created, I ran the below command to fetch the decoded secret. 
$ kubectl get secret jx-jx-app-jenkins -o yaml | ~/go/src/github.com/mfuentesg/ksd/ksd

RESULT: Encoded file returned.
Expected Result: Decoded file/ secret.

No where found anything related to this, could someone help me out with this or it's a bug in KSD.

**Comment by mfuentesg** [comment]
Fixed on the current version.
